minimumReleaseAge: 10080
minimumReleaseAgeExclude: []
onlyBuiltDependencies: []
strictDepBuilds: true
blockExoticSubdeps: true
trustPolicy: no-downgrade

# TODO: vitepress を使わない
allowBuilds:
  esbuild: ""
trustPolicyExclude:
  - semver
  - vite
