minimumReleaseAge: 10080 # 7 日
minimumReleaseAgeExclude: []
onlyBuiltDependencies: []
strictDepBuilds: true
blockExoticSubdeps: true
trustPolicy: no-downgrade
update:
  ignoreDeps:
    - "*" # パッケージの更新は ncu に任せる

# TODO: vitepress を使わない
allowBuilds:
  esbuild: true
trustPolicyExclude:
  - semver
  - vite
